# Generated by Django 4.0.3 on 2022-07-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavComics',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comic_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('onsaledate', models.DateField()),
                ('characters', models.TextField()),
                ('added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
