# Generated by Django 4.0.3 on 2022-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getfavorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavcomics',
            name='characters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
